### ISSUE TITLE
Different result from docs with default sequence

### ISSUE THREAD

**Issue by flashton2003** [adelq/dnds#1]
I'm running dnds with python 2.7 installed via cloning the github repo. When I run the below command

`python ~/Dropbox/programs/dnds/dnds.py`

It returns the result 0.642189586115. This is different from the result of 0.86 on https://github.com/adelq/dnds

Why is this? Thanks for the nice package!

**Comment by adelq** [comment]
I'm glad you like it!

Yup, that value is expected for the sequences in `dnds.py`, the README is using the test sequences from `test_dnds.py`. I'll fix the README documentation to be more explicit about what `sequence_1` and `sequence_2` refer to. Thanks for the notice!
