### ISSUE TITLE
Gaps and table 11 for genetic code.

### ISSUE THREAD

**Issue by shimbalama** [adelq/dnds#6]
Hi - nice to see a python implementation! 

Are you able to modify this to specify the genetic code (11 for bacteria) and to take multiple sequence alignments with gaps and Ns and calculate all dnds Vs a reference sequence?

Regards,
Liam

**Comment by adelq** [comment]
Hi Liam,

Thanks! At present, no - the codon translation is done with a simple generic code table, but could easily be retrofitted to use BioPython's powerful genetic code translation. I'm not sure about how you would deal with gaps and Ns though. Did you have something in mind for how you would handle them?

**Comment by shimbalama** [comment]
I did it like this https://github.com/biopython/biopython/blob/master/Doc/doc.rst

**Comment by shimbalama** [comment]
Or more specifically:

seq1 = SeqRecord(Seq(str(ref.seq), alphabet=IUPAC.IUPACUnambiguousDNA()), id='pro1')
            seq2 = SeqRecord(Seq(str(record.seq), alphabet=IUPAC.IUPACUnambiguousDNA()), id='pro2')

            #aln prot
            tmp_aln = p+'tmp.aln'
            tmp_fa = p+'tmp.fa'
            with open(p+'tmp.fa','w') as fout:
                for seqxx in [ref, record]:
                    record_prot = SeqRecord(Seq(str(seqxx.seq),generic_dna), id=seqxx.id)
                    record_prot.seq = record_prot.seq.translate(table=11)
                    SeqIO.write(record_prot, fout, 'fasta')
            cline = MuscleCommandline(input=tmp_fa,out=tmp_aln)
            stdout1,stderr1 = cline()

            #add prot
            for i, aa_record in enumerate(SeqIO.parse(p+'/tmp.aln','fasta')):
                if aa_record.id == ref.id:
                    pro1 = SeqRecord(Seq(str(aa_record.seq), alphabet=IUPAC.protein),id='pro1')
                else:
                    pro2 = SeqRecord(Seq(str(aa_record.seq), alphabet=IUPAC.protein),id='pro2')

            #muake aln object
            aln = MultipleSeqAlignment([pro1, pro2])
            codon_aln = codonalign.build(aln, [seq1, seq2])

            #get dnds
            dN, dS = cal_dn_ds(codon_aln[0], codon_aln[1], method='NG86')

**Comment by shimbalama** [comment]
That handles gaps and Ns and any table. And does dN, dS.

**Comment by adelq** [comment]
I think this level of functionality is out of scope for this project - pulling in BioPython (or part of it) for codon translation tables, alignment, and handling unknown bases. Given that BioPython appears to have this functionality, I would recommend using it over dnds for your usecase. Thanks for the suggestion!
