### ISSUE TITLE
Can the result from dnds be compared with yn00 of PAML

### ISSUE THREAD

**Issue by hongzhonglu** [adelq/dnds#8]
Dear Adel,
I am interested in dn/ds caluclation. Can the result from dnds be compared with yn00 of PAML as the later is vey popular in this aspect?

Best regards,
Hongzhong

**Comment by adelq** [comment]
Dear Hongzhong,

I'm not sure to be honest, I have never done a head-to-head comparison. If you find any discrepancies or specific points of comparisons you would like to add to the README, I would be happy to include them!

Best,
Adel
